app:
    jwtExpirationInMs: 86400000
    jwtSecret: B4uN051lvABarb05A
server:
    port: ${port:8080}
spring:
    profiles:
        active: "dev"
    jackson:
        date-format: dd/MM/yyyy HH:mm:ss
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
            fail-on-empty-beans: false
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: false

---

spring:
    profiles: dev
    datasource:
        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driver-class-name: org.h2.Driver
        platform: h2
    h2:
        console:
        enabled: true
        path: /h2-console
---
spring:
    profiles: prod
    datasource:
        initialization-mode: always
        password: ${POSTGRES_PASSWORD:postgres}
        url: jdbc:postgresql://${srv-captain--expense-control-db:localhost}:5432/${POSTGRES_DB:expensecontrol}
        username: ${POSTGRES_USER:postgres}